spring:
    application:
        name: customer-microservice
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: ${DATABASE_DRIVER}

server:
    port: ${SERVER_PORT:3030}
